### PR TITLE
Refactoring 

### PR DESCRIPTION
**Pull request by frapac**
- add varying bounds for states and controls
- fix HereAndNow SDDP 
- add `iterate!` function to ease dual SDDP code
- drop julia 0.5 support

### CODE REVIEW

**Comment by odow** [comment]
When do we get to see the dual code? :) I'm very interested

**Comment by frapac** [comment]
I was planning to release it after the publication of the article on arxiv, but I have been a bit busy since :p 

If you are interested, I can tidy up the code and release it by the end of the week!

**Comment by odow** [comment]
No rush, you have your thesis to finish!

**Comment by frapac** [comment]
@odow I released dual SDDP in this repo:
https://github.com/frapac/DualSDDP.jl

To use dual SDDP, you should be on the branch `fp/refact` in StochDynamicProgramming. 

I give some example in a jupyter notebook. The code is not that clean, but I hope it conveys well the ideas behind dual SDDP :) 

I think that writing the dual SP should be straightforward with MOI, as we have access to the Linear Bellman operator coded directly as a LP and we have access to the corresponding matrix. I plan to implement this after the JuMP dev workshop, in a new version of SDDP in JuliaStochOpt.

Do not hesitate if you have any remark concerning the code/the algorithm!

**Comment by odow** [comment]
I'm very pleased to see this. Great work. I'm submitting my thesis Tuesday so will look properly after then.

**Comment by frapac** [comment]
Good luck for the final rush!

**Pull request merged**
